apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksworkshop-9804"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksworkshop-9804"
  template:
    metadata:
      labels:
        app: "aksworkshop-9804"
    spec:
      containers:
        - name: "aksworkshop-9804"
          image: "shengrossacrworkshop.azurecr.io/aksworkshop"
          ports:
          - containerPort: 80