apiVersion: v1
kind: Service
metadata:
    name: "akslabv2-4046"
    labels:
        app: "akslabv2-4046"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "akslabv2-4046"