on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: arcakslabv2.azurecr.io
        username: ${{ secrets.acr_arcakslabv2_username }}
        password: ${{ secrets.acr_arcakslabv2_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t arcakslabv2.azurecr.io/akslabv2:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push arcakslabv2.azurecr.io/akslabv2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akslabv2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akslabv2882e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akslabv2882e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akslabv2882e
        container-registry-url: arcakslabv2.azurecr.io
        container-registry-username: ${{ secrets.acr_arcakslabv2_username }}
        container-registry-password: ${{ secrets.acr_arcakslabv2_password }}
        secret-name: akslabv2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akslabv2882e
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          arcakslabv2.azurecr.io/akslabv2:${{ github.sha }}
        imagepullsecrets: |
          akslabv2dockerauth
